# Site settings
title: Forecasting Volatility
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://megacookies88.github.io/forecasting-stock-volatility/" # the base hostname & protocol for your site

twitter_username: MegaCookies88
github_username1: MegaCookies88
github_username2: nourGhribi

# Build settings
markdown: kramdown
